query getProduct($handle: String!) {
  productByHandle(handle: $handle) {
    id
    title
    description
    handle
    images(first: 5) {
      edges {
        node {
          originalSrc
          thumbnail: transformedSrc(maxWidth: 150)
          altText
        }
      }
    }
    priceRange {
      minVariantPrice {
        amount
        currencyCode
      }
    }
    options(first: 5) {
      id
      name
      values
    }
    variants(first: 25) {
      edges {
        node {
          id
          title
          availableForSale
          priceV2 {
            amount
          }
          image {
            altText
            originalSrc
          }
          selectedOptions {
            name
            value
          }
        }
      }
    }
    collections(first: 1) {
      edges {
        node {
          title
          products(first: 5) {
            edges {
              node {
                title
                handle
                id
                priceRange {
                  minVariantPrice {
                    amount
                  }
                }
                images(first: 1) {
                  edges {
                    node {
                      originalSrc
                      altText
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
