query getProductsInCollection($handle: String!) {
  collection(handle: $handle) {
    title
    products(first: 4) {
      edges {
        node {
          ...productFields
          priceRange {
            minVariantPrice {
              ...moneyV2Fields
            }
          }
          featuredImage {
            ...imageFields
          }
        }
      }
    }
  }
}
fragment imageFields on Image {
  url
  altText
}
fragment productFields on Product {
  id
  title
  handle
}
fragment moneyV2Fields on MoneyV2 {
  amount
  currencyCode
}
