query getProduct($handle: String!) {
  product(handle: $handle) {
    ...productFields
    description
    options(first: 5) {
      id
      name
      values
    }
    variants(first: 25) {
      edges {
        node {
          id
          title
          availableForSale
          priceV2 {
            ...moneyV2Fields
          }
          image {
            ...imageFields
          }
          selectedOptions {
            name
            value
          }
        }
      }
    }
    collections(first: 1) {
      edges {
        node {
          title
          products(first: 5) {
            edges {
              node {
                ...productFields
                priceRange {
                  minVariantPrice {
                    ...moneyV2Fields
                  }
                }
                featuredImage {
                  ...imageFields
                }
              }
            }
          }
        }
      }
    }
  }
}
fragment imageFields on Image {
  url
  altText
}
fragment productFields on Product {
  id
  title
  handle
}
fragment moneyV2Fields on MoneyV2 {
  amount
  currencyCode
}
