name: 'Chromatic'
on: push

env:
  NODE_VERSION: '>=16.x'
  PNPM_VERSION: '>=7.x'

jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.3
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        id: cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN  }}
          exitZeroOnChanges: true
          autoAcceptChanges: true
          exitOnceUploaded: true
          ignoreLastBuildOnBranch: 'main'
        env:
          NEXT_PUBLIC_SHOPIFY_STORE_ID: ${{ secrets.SHOPIFY_STORE_ID }}
          NEXT_PUBLIC_SHOPIFY_API_TOKEN: ${{ secrets.SHOPIFY_API_TOKEN }}
